# Generated by Django 5.2.10 on 2026-01-14 08:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('markdown', 0), ('paragraph', 1), ('heading', 2), ('image', 3), ('code', 6), ('raw_html', 7), ('quote', 5)], blank=True, block_lookup={0: ('wagtailmarkdown.blocks.MarkdownBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Language hint for syntax highlighting (e.g. python, js).', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('code', 5)]], {}), 7: ('wagtail.blocks.RawHTMLBlock', (), {})}),
        ),
    ]
