# Generated by Codex on 2026-01-21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('markdown', 0), ('paragraph', 1), ('heading', 2), ('image', 3), ('code', 6), ('raw_html', 7), ('quote', 5), ('collapsible', 11)], blank=True, block_lookup={0: ('wagtailmarkdown.blocks.MarkdownBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Language hint for syntax highlighting (e.g. python, js).', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('code', 5)]], {}), 7: ('wagtail.blocks.RawHTMLBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': "The summary text shown when collapsed (e.g., 'Click to reveal')", 'required': True}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'If checked, the content will be visible by default', 'required': False}), 10: ('wagtail.blocks.StreamBlock', [[('markdown', 0), ('paragraph', 1), ('heading', 2), ('image', 3), ('code', 6), ('raw_html', 7), ('quote', 5)]], {'help_text': 'The content to show when expanded'}), 11: ('wagtail.blocks.StructBlock', [[('category', 12), ('title', 8), ('open_by_default', 9), ('content', 10)]], {}), 12: ('wagtail.blocks.ChoiceBlock', (), {'choices': [('explainer', 'Explainer'), ('technical', 'Technical'), ('extra', 'Extra')], 'default': 'explainer', 'help_text': 'Choose a category to color-code the collapsible.', 'required': False})}),
        ),
    ]
