# Generated by Codex on 2026-01-21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("markdown", 0),
                    ("paragraph", 1),
                    ("heading", 2),
                    ("image", 3),
                    ("code", 6),
                    ("raw_html", 7),
                    ("quote", 5),
                    ("collapsible", 11),
                    ("glossary", 15),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    3: ("wagtail.blocks.StructBlock", [[("image", 13), ("caption", 14)]], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Language hint for syntax highlighting (e.g. python, js).",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.TextBlock", (), {}),
                    6: ("wagtail.blocks.StructBlock", [[("language", 4), ("code", 5)]], {}),
                    7: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The summary text shown when collapsed (e.g., 'Click to reveal')",
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, the content will be visible by default",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("markdown", 0),
                                ("paragraph", 1),
                                ("heading", 2),
                                ("image", 3),
                                ("code", 6),
                                ("raw_html", 7),
                                ("quote", 5),
                                ("glossary", 15),
                            ]
                        ],
                        {"help_text": "The content to show when expanded"},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 12), ("title", 8), ("open_by_default", 9), ("content", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        (),
                        {
                            "choices": [
                                ("", "Default"),
                                ("explainer", "Explainer"),
                                ("technical", "Technical"),
                                ("extra", "Extra"),
                                ("subquest", "SubQuest"),
                            ],
                            "default": "",
                            "help_text": "Optional category to color-code the collapsible.",
                            "required": False,
                        },
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional caption shown under the image.", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("terms", 16), ("auto_link", 18), ("show_list", 19)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"help_text": "Glossary terms for this post."},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 20), ("definition", 21), ("aliases", 22)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Auto-link matching terms in the post body.",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show a glossary list at this position.",
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    21: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional aliases (comma-separated).", "required": False},
                    ),
                },
            ),
        ),
    ]
