# Generated by Django 5.2.10 on 2026-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body_render_cache_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_rendered_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_rendered_readtime_deep',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_rendered_readtime_main',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_rendered_toc_crumb',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_rendered_toc_items',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
